version: '3.7'

services:
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    depends_on:
      - redis
    ports:
      - '8080:8080'
    env_file:
      - my.env
      - secret.env
    volumes:
      - "./authenticated-emails:/etc/oauth2-proxy/authenticated-emails"
  redis:
    image: redis:6.2
  dummy:
    build:
      context: .
      dockerfile: Dockerfile
